# Generated by Django 2.1.1 on 2018-09-28 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0002_auto_20180927_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='labels_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes_app.Note'),
        ),
    ]
